[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.4"
http = "1.1.0"
log = "0.4.21"
tracing-subscriber = "0.3.18"
serde = { version = "1.0.197", features = ["derive"] }
tokio = { workspace = true }
chrono = "0.4.38"
serde_with = "3.7.0"
